VoxelGrid
std::vector<Voxel> VoxelGrid::voxels
Referenced by addVoxel, createEdgeIndex, createNodeFeatures, PYBIND11_MODULE, toList.
VoxelGrid::VoxelGrid()
void VoxelGrid::addVoxel(int x, int y, int z, pybind11::object data=pybind11::int_(1))
References voxels.
Referenced by PYBIND11_MODULE.
std::vector< std::tuple< int, int, int > > VoxelGrid::toList() const
References voxels.
Referenced by PYBIND11_MODULE.
std::pair< std::vector< std::vector< float > >, std::vector< std::pair< int, int > > > VoxelGrid::toGraph(int xDim, int yDim, int zDim, float neighboring_radius=1.0)
References createEdgeIndex, createNodeFeatures.
Referenced by PYBIND11_MODULE.