OctreeInternalNode
std::vector<std::shared_ptr<OctreeNode> > OctreeInternalNode::children_
Referenced by GetChild, GetChildren, SetChild, ToBitString.
OctreeInternalNode::OctreeInternalNode()
bool OctreeInternalNode::IsLeaf() const override
std::shared_ptr< OctreeNode > OctreeInternalNode::GetChild(size_t index) const
References children_.
Referenced by PYBIND11_MODULE, ToJson.
const std::vector< std::shared_ptr< OctreeNode > > & OctreeInternalNode::GetChildren() const
References children_.
size_t OctreeInternalNode::GetChildIndex(const Eigen::Vector3d &point, const Eigen::Vector3d &origin, double size) const
void OctreeInternalNode::SetChild(size_t index, std::shared_ptr< OctreeNode > child)
References children_.
std::string OctreeInternalNode::ToBitString() const override
References children_.
Referenced by PYBIND11_MODULE.
std::string OctreeInternalNode::ToJson(int indent=0) const override
References GetChild.
Referenced by PYBIND11_MODULE.