Octree
Eigen::Vector3d Octree::origin_
Referenced by InsertPoint, LocateLeafNode.
double Octree::size_
Referenced by InsertPoint, LocateLeafNode.
size_t Octree::max_depth_
Referenced by InsertPointRecurse.
std::shared_ptr<OctreeNode> Octree::root_
Referenced by InsertPoint, LocateLeafNode, ToBitString, ToJson.
Octree::Octree(const Eigen::Vector3d &origin, double size, size_t max_depth)
void Octree::InsertPoint(const Eigen::Vector3d &point)
References InsertPointRecurse, origin_, root_, size_.
Referenced by PYBIND11_MODULE.
std::shared_ptr< OctreeLeafNode > Octree::LocateLeafNode(const Eigen::Vector3d &point) const
References origin_, root_, size_.
Referenced by PYBIND11_MODULE.
std::string Octree::ToBitString() const
References root_.
Referenced by PYBIND11_MODULE.
std::string Octree::ToJson(int indent=0) const
References root_.
Referenced by PYBIND11_MODULE.
void Octree::InsertPointRecurse(const std::shared_ptr< OctreeNode > &node, const Eigen::Vector3d &point, const Eigen::Vector3d &origin, double size, size_t depth)
References max_depth_.
Referenced by InsertPoint.