voxel.cpp
std::vector< std::vector< float > > createNodeFeatures(const VoxelGrid &grid)
References VoxelGrid::voxels.
Referenced by VoxelGrid::toGraph.
std::vector< std::pair< int, int > > createEdgeIndex(const VoxelGrid &grid, float neighboring_radius)
References calculateDistance, VoxelGrid::voxels.
Referenced by VoxelGrid::toGraph.
float calculateDistance(const Voxel &v1, const Voxel &v2)
References Voxel::x, Voxel::y, Voxel::z.
Referenced by createEdgeIndex.